name: ct
channels:
  - bioconda
  - conda-forge
dependencies:
  - biopython
  - dendropy
  - numpy
  - r-ape
  - r-dplyr
  - r-geiger
  - r-readr
  - r-tibble
  - scipy
  - setuptools

prefix: "/home/mramon/micromamba/envs/ct"
